---
title: "IBI score report"
author: "Frank"
date: "`r format(Sys.Date())`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8)
```

```{css, echo=FALSE}
h1, h4 {
  text-align: center;
  color: black;
  font-weight: bold;
}
```

## Introduction

This is sample report for IBI score calculations of sites collected in 2012. 

### Import dataset

```{r import excel file,warning=FALSE,echo=FALSE}
library(DT)
library(readxl)
comb_2012 <- read_excel("F:/One Drive - Towson U/Thesis stuff/Data/Benthic data/D-net (MBSS)/IBI scores from MBSS package/2012/R benthic data 2012.xlsx", 
                        sheet = "Combine")
```

### Set up arguments for later calculation

```{r function}
library(MBSStools)
# Metrics, Index, Benthic Macroinvertebrates, genus
# (generate values then scores)
myIndex <- "MBSS.2005.Bugs"
# Thresholds
thresh <- metrics_scoring
# get metric names for myIndex
(myMetrics.Bugs.MBSS <- as.character(droplevels(unique(thresh[thresh[,"Index.Name"]==myIndex,"MetricName.Other"]))))
# Add Narrative
myBreaks <- c(1:5)
myLabels <- c("Very Poor", "Poor", "Fair", "Good")
```

### Calculate metric values

```{r run once,results='hide'}
comb_2012_metric <- metric.values(comb_2012, "bugs",myMetrics.Bugs.MBSS)
```

### Calculate IBI scores and Add Narrative

```{r,message=F,results='hide'}
# SCORE
comb_2012_metric_scores <- metric.scores(comb_2012_metric,myMetrics.Bugs.MBSS, "INDEX.NAME", "STRATA_R", thresh)
# View Results
comb_2012_metric_scores

# Add Narrative
comb_2012_metric_scores$IBI_Nar <- cut(comb_2012_metric_scores$IBI
                                     , breaks=myBreaks
                                     , labels=myLabels
                                     , include.lowest=TRUE
                                     , right=FALSE
                                     , ordered_result=TRUE)
# QC, IBI Numeric vs. Narrative
table(comb_2012_metric_scores$IBI
      , comb_2012_metric_scores$IBI_Nar
      , useNA="ifany")
comb_2012_metric_scores
```

### Table of IBI scores

```{r,message=F}
datatable(comb_2012_metric_scores, rownames = F,  options= list(scrollX = TRUE, pageLength = nrow(comb_2012_metric_scores), dom='t'), selection = 'none') 
```

